:paypal:
  :form:
    :amount: 7.00
    :business: payments@bylinebreak.com
    :cmd: _xclick
    :discount_rate: 0
    :discount_rate2: 10
    :cancel_return: http://www.getbaseapp.com/cancel
    :cert_id: CGLV62AYHWK7A
    :currency_code: EUR
    :item_name: BaseApp 1.x
    :notify_url: http://www.getbaseapp.com/ipn
    :return: http://www.getbaseapp.com/thanks
  :url: https://www.paypal.com/cgi-bin/webscr
